export const MAX_POST_TITLE_CHARS = 300;
export const MAX_POST_BODY_CHARS = 40000;
export const MAX_COMMENT_BODY_CHARS = 3000;
export const MAX_LLM_EXCERPT_CHARS = 1800;
export const MAX_LLM_CANDIDATES = 5;

export const bodySignals = {
  hard: [
    'dies',
    'die',
    'death',
    'dead',
    'killed',
    'kill',
    'murder',
    'murdered',
    'assassinated',
    'slain',
    'shot',
    'stabbed',
    'beheaded',
    'executed',
    'ending',
    'finale',
    'season finale',
    'series finale',
    'final scene',
    'last scene',
    'post credit',
    'post-credits',
    'mid credits',
    'mid-credits',
    'plot twist',
    'twist ending',
    'the ending is',
    'it was all a dream',
    'final boss',
    'main villain',
    'true villain',
    'betrays',
    'betrayed',
    'traitor',
    'identity reveal',
    'secret identity',
    'identity is',
    'the killer is',
    'who dies',
    'who killed',
    'revealed to be',
    'is revealed',
  ],
  medium: [
    'spoiler',
    'spoilers',
    'spoiler warning',
    'episode',
    'episodes',
    'chapter',
    'chapters',
    'volume',
    'leak',
    'leaks',
    'leaked',
    'rumor',
    'rumour',
    'confirmed',
    'confirmation',
    'ending explained',
    'explained ending',
    'major reveal',
    'big reveal',
    'reveal',
    'after credits',
    'post credits scene',
    'post-credits scene',
    'credit scene',
    'scene after credits',
    'season ending',
    'series ending',
    'final episode',
    'series finale',
    'season finale',
    'cliffhanger',
    'identity',
    'killer',
    'dies in',
    'death scene',
  ],
} as const;

export const speculationSignals = [
  'prediction',
  'predictions',
  'theory',
  'theories',
  'speculation',
  'speculative',
  'guess',
  'guessing',
  'might',
  'may',
  'could',
  'probably',
  'possibly',
  'seems like',
  'i think',
  'i bet',
  'my guess',
  'next season',
  'future season',
  'next episode',
  'eventually',
] as const;

export const confirmationSignals = [
  'i watched it',
  'i saw it',
  'i saw this',
  'i watched this',
  'confirmed',
  'actually dies',
  'actually dies in',
  'he dies',
  'she dies',
  'they die',
  'it happens',
  'this happens',
  'that happens',
  'in the episode',
  'in the movie',
  'in the finale',
  'spoiler',
  'spoilers',
  'leaked',
  'leak',
] as const;
